spring:
  application:
    name: wallet-ledger-service
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet-ledger-service?currentSchema=wallet-ledger-service&options=-c%20TimeZone=UTC
    username: wallet-ledger-service
    password: wallet-ledger-service
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 500ms
      timeout: 500ms
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: wallet-ledger-service
    password: wallet-ledger-service
    connection-timeout: 2s
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  grpc:
    server:
      port: 9090

wallet-ledger-service:
  rabbitmq:
    wallet-event-exchange: wallet.event
    confirm-timeout: 2s
  publisher:
    wallet-updated-outbox:
      batch-size: 10
      processing-lock-ttl: 60s
      retry-delay: 5s
      fixed-delay-ms: 1000
      max-attempts: 10
  redis:
    lock-key-prefix: 'wallet:lock:'
    lock-timeout: 10s
    lock-retry-attempts: 10
    lock-retry-backoff: 100ms
